# -*- coding: utf-8 -*-
"""Copy of Untitled144.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f8ZlFZjcCUvnUBRNvWUn0NLULW894aPH
"""

# Commented out IPython magic to ensure Python compatibility.
#import some Library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

#Load csv File
df = pd.read_csv("/content/Diwali Sales Data.csv",encoding = "unicode_escape")

#to print first 5 rows
df.head()

#Print Last 5 rows
df.tail()

df.shape

df.isnull().sum()

"""DATA CLEANING"""

df.drop(["Status","unnamed1"],inplace=True,axis=1)

df.dropna(inplace=True)

df.isnull().sum()

df.describe()

df["Amount"]=df["Amount"].astype("int")

df["Amount"].dtype

df.columns

df[["Age","Orders","Amount"]].describe()

"""##EDA(Exploratory Data Analysis)"""

#Gender

ax = sns.countplot(x="Gender", data=df)

for bars in ax.containers:
  ax.bar_label(bars)

sales_gen = df.groupby(["Gender"],as_index=False)["Amount"].sum().sort_values(by="Amount",ascending=False)

ax = sns.barplot(x="Gender",y="Amount",data = sales_gen)
for bars in ax.containers:
  ax.bar_label(bars)

"""From above graph we can see tat most of the buyers female and even the purchasing power of female are greater than men

#age
"""

sns.countplot(x="Age Group",data=df,hue="Gender")

ax = sns.countplot(x="Age Group",data = df,hue = "Gender")
for bars in ax.containers:
  ax.bar_label(bars)

sales_age = df.groupby(["Age Group"],as_index=False)["Amount"].sum().sort_values(by="Amount",ascending = False)
ax=sns.barplot(x = "Age Group",y="Amount",data = sales_age)

"""from above graph we can see that most of the buyers age group between 26-35 years female

###States
"""

#total numbers of orders from top 10 states

sales_state = df.groupby(["State"],as_index = False)["Orders"].sum().sort_values(by = "Orders",ascending = False).head(10)
sns.set(rc={'figure.figsize':(25,7)})
sns.barplot(data=sales_state,x="State",y="Orders")

#amount/sales from top 10 states

sales_state = df.groupby(["State"], as_index=False)["Amount"].sum().sort_values(by="Amount",ascending= False).head(10)
sns.set(rc={"figure.figsize":(25,7)})
sns.barplot(data=sales_state,x="State",y="Amount")

"""from above graph we can see that unexpectually most of the orders are from uttar pradesh ,maharashtra and karnataka respectively and total sales/amoiunt is from up ,maharashtra and karnataka"""

ax = sns.countplot(data=df,x ="Marital_Status")
sns.set(rc={"figure.figsize":(20,5)})
for bars in ax.containers:
  ax.bar_label(bars)

sales_state = df.groupby(["Marital_Status","Gender"],as_index =False)["Amount"].sum().sort_values(by="Amount",ascending = False)
sns.set(rc={"figure.figsize":(6,5)})
sns.barplot(data=sales_state,x="Marital_Status",y= "Amount",hue="Gender")

"""##Occupations"""

ax = sns.countplot(data=df,x="Occupation")
sns.set(rc={"figure.figsize":(25,11)})
for bars in ax.containers:
  ax.bar_label(bars)

sales_state = df.groupby(["Occupation"],as_index = False)["Amount"].sum().sort_values(by = "Amount",ascending = False)
sns.barplot(data=sales_state,x="Occupation",y="Amount")

"""from above graph we can see that most of the buyers sre from it sector,helthcare,aviation

##PRODUCT CATEGORY
"""

ax=sns.countplot(data = df, x = "Product_Category")
sns.set(rc={"figure.figsize":(25,15)})
for bars in ax.containers:
  ax.bar_label(bars)

sales_state = df.groupby(["Product_Category"],as_index = False)["Amount"].sum().sort_values(by="Amount",ascending=False).head(10)
sns.barplot(data=sales_state , x="Product_Category" , y="Amount")
sns.set(rc={"figure.figsize":(35,29)})

"""most sold product food,clothing and electronic gadget

##CONCLUSION

####Married women age group 26_35 yrs from up ,maharashtra  and  karnataka working in IT,Helthcare & aviation are more likely to buy products from food clothing and electronic category
"""